### ISSUE TITLE
Proxima fix in the Button component

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1873] opened 2020-07-23 08:08 UTC
Hi

This fix is more likely for the Proxima font on Linux/macOS
https://github.com/brainly/style-guide/blob/0319fe5bcc422dfec3eaf19bfb5b886a671bcd47/src/components/buttons/_buttons.scss#L95-L99

But on the other hand, I think this fix kind of not useful with Proxima font on Windows

Before disabling `top` | After disabling
--- | ---
![image](https://user-images.githubusercontent.com/5789670/88260188-8d0c2700-cccc-11ea-91b1-1091806e22dc.png) | ![image](https://user-images.githubusercontent.com/5789670/88260238-a3b27e00-cccc-11ea-845f-58191b470678.png)

OS-specific solution for this issue is required.

**Comment by kubajasiolek** [comment] 2020-07-27 09:59
@seahindeniz You may try something like this and use it with `top` set to 0:
```scss
  &::before {
    content: ' ';
    width: 0;
    font-family: Arial, Verdana, sans-serif;
  }
```

**Comment by seahindeniz** [comment] 2020-07-27 11:04
Hey @kubajasiolek 
Thanks for the suggestion. I have already found a workaround on my end. I was mentioning this because the text wrapper in the Button and also some other components has this issue it's also affecting the Brainly web app too

It's not a big issue of course but there it is 🙂 
![image](https://user-images.githubusercontent.com/5789670/88534939-bf41bf80-d011-11ea-8583-3e8a61aa25d6.png)

**Comment by kubajasiolek** [comment] 2020-07-27 11:10
Let's leave it open - I or somebody else may take a look in the future :)

**Comment by clxandstuff** [comment] 2021-08-31 12:31
Hi @seahindeniz 
Looks like it has been already fixed. I tried to reproduce this on Firefox (91.0.2 Ubuntu) and Chrome (86.0) with no luck. Can you check once again if this still occurs in your browser?

**Comment by clxandstuff** [comment] 2021-09-01 09:15
@seahindeniz 
I'm closing this issue. If you will have further problems please open new one.

**Closed by clxandstuff** 2021-09-01 09:15 UTC
Labels: Status: Obsolete
